#!/bin/bash
case $1 in
  -v)
    LEVEL=V
    ;;
  *)
    LEVEL=D
    ;;
esac

ADB_LOG="/home/laputa/dev/sdk/platform-tools/adb logcat"
LOG_FILE="/tmp/$(basename $0).$RANDOM.log"
touch $LOG_FILE
$ADB_LOG -c
$ADB_LOG GST-dbg:$LEVEL GNAP-debug:$LEVEL dalvikvm:$LEVEL AndroidRuntime:$LEVEL DEBUG:$LEVEL *:E &>$LOG_FILE &
pid=$!

trap "kill $pid; rm -f $LOG_FILE;exit" SIGHUP SIGINT SIGTERM

tail -f $LOG_FILE | \
awk '{
  if(index($1, "GST-dbg")>0) {
    printf("%-10s", $7);
    printf("%30s: ", $8);
    for (i=9; i <= NF; i++)
      printf("%s ", $i);
    printf("\n");
  }else {
    for (i = 1;i <= NF;i++)
      printf("%s ", $i);
    printf("\n");
  }
}'
